export default IMAGES = {
  Avatar1: '../assets/images/a1.png',
  Avatar2: '../assets/images/a2.png',
  Avatar3: '../assets/images/a3.png',
  Avatar4: '../assets/images/a4.png',
  Female1: '../assets/images/f1.jpg',
  Female2: '../assets/images/f2.jpg',
  Female3: '../assets/images/f3.jpg',
  Female4: '../assets/images/f4.jpg',
  Female5: '../assets/images/f5.jpg',
  Male1: '../assets/images/m1.jpg',
  Male2: '../assets/images/m2.jpg',
  Male3: '../assets/images/m3.jpg',
  Male4: '../assets/images/m4.jpg',
  Male5: '../assets/images/m5.jpg',
  Face1: '../assets/images/face1.jpg',
  Face2: '../assets/images/face2.jpg',
  Face3: '../assets/images/face3.jpg',
  Face4: '../assets/images/face4.jpg',
  Face5: '../assets/images/face5.jpg',
};
