export default IMAGES = {
  Avatar1: require('../assets/images/a1.png'),
  Avatar2: require('../assets/images/a2.jpeg'),
  Avatar3: require('../assets/images/a3.jpg'),
  Avatar4: require('../assets/images/a4.jpg'),
  Female1: require('../assets/images/f1.jpg'),
  Female2: require('../assets/images/f2.jpg'),
  Female3: require('../assets/images/f3.jpg'),
  Female4: require('../assets/images/f4.jpg'),
  Female5: require('../assets/images/f5.jpg'),
  Male1: require('../assets/images/m1.jpg'),
  Male2: require('../assets/images/m2.jpg'),
  Male3: require('../assets/images/m3.jpg'),
  Male4: require('../assets/images/m4.jpg'),
  Male5: require('../assets/images/m5.jpg'),
  Face1: require('../assets/images/face1.jpg'),
  Face2: require('../assets/images/face2.jpeg'),
  Face3: require('../assets/images/face3.jpg'),
  Face4: require('../assets/images/face4.jpg'),
  Face5: require('../assets/images/face5.jpg'),
};
